/* Generated By:JavaCC: Do not edit this line. JSONConstants.java */
package org.beanstalk4j.json;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
interface JSONConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INTEGER = 5;
  /** RegularExpression Id. */
  int TRUE = 6;
  /** RegularExpression Id. */
  int FALSE = 7;
  /** RegularExpression Id. */
  int NULL = 8;
  /** RegularExpression Id. */
  int STRING = 9;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<INTEGER>",
    "\"true\"",
    "\"false\"",
    "\"null\"",
    "<STRING>",
    "\"{\"",
    "\"}\"",
    "\",\"",
    "\":\"",
  };

}
